### ISSUE TITLE
Edit episode: Interview with Adilson

### ISSUE THREAD

**Issue by schalkneethling** [The-Mycelium-Network/podcast#19]

**Comment by schalkneethling** [comment]
Hey @TremaineNeethling,

How are you doing on this one? I would like to review it today and schedule it for publishing. Thanks!

**Comment by schalkneethling** [comment]
Hey @TremaineNeethling,

How is this one coming along? Ready for me to review? Thanks.

**Comment by TremaineNeethling** [comment]
Hey @schalkneethling 

This episode is ready for review.

**Comment by schalkneethling** [comment]
> Hey @schalkneethling
> 
> This episode is ready for review.

Thanks! I will review it.
